PortfolioA/posts/urls.py
from django.urls import path
from .views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),

]

PortfolioA/users/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path("users/", include("PortfolioA.users.urls")),
    path("posts/", include("PortfolioA.posts.urls")),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

PortfolioA/posts/models.py
from django.db import models

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,   # 한 줄 건너뛰어서 괄호를 닫았으니 ,을 찍어야 한다.
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE) # 바로 닫았으니 , 필요없음
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

PortfolioA/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser # 추가

class User(AbstractUser):
    profile_image = models.ImageField("프로필 이미지", upload_to="users/profile", blank=True)
    short_description = models.TextField("소개글", blank=True)
    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name="좋아요 누른 Post 목록",
        related_name="like_users",
        blank=True,
    )
    following = models.ManyToManyField(
        "self",
        verbose_name="팔로우 중인 사용자들",
        related_name="followers",
        symmetrical=False,
        through="users.Relationship",
    )

    def __str__(self):
        return self.username

class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우를 요청한 사용자",
        related_name="following_relationships",
        on_delete=models.CASCADE,
    )
    to_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청의 대상",
        related_name="follower_relationships",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"관계 ({self.from_user} -> {self.to_user})"

PortfolioA/posts/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

PortfolioA/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        ),
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)  # 회원가입시 ***으로 보여진다.
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자면({username})은 이미 사용 중입니다")
        return username

    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            # password2 필드에 오류를 추가
            self.add_error("password2", "비밀번호가 일치하지 않습니다")

    def save(self):
        username = self.cleaned_data['username']
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        profile_image = self.cleaned_data['profile_image']
        short_description = self.cleaned_data['short_description']
        user = User.objects.create_user(
            username=username,
            password=password1,
            profile_image=profile_image,
            short_description=short_description,
        )
        return user

PortfolioA/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment, PostImage, HashTag
from .forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

def feeds(request):
    # 요청에 포함된 사용자가 로그인하지 않은 경우
    if not request.user.is_authenticated:
        return redirect("/users/login/")

    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
               }
    return render(request, "PortfolioA/posts/feeds.html", context)

@require_POST   # 댓글 작성을 처리할 View, Post 요청만 허용한다.
def comment_add(request):
    # request.POST로 전달된 데이터를 사용해 CommentForm 인스턴스를 생성
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # commit=False 옵션으로 메모리상에 Comment 객체 생성
        comment = form.save(commit=False)

        # Comment 생성에 필요한 사용자 정보를 request에서 가져와 할당
        comment.user = request.user

        # DB에 Comment 객체 저장
        comment.save()

        # URL로 'next' 값을 전달받았다면, 댓글 작성 완료 후 전달받은 값으로 이동한다
        url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url_next)

@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
        return HttpResponseRedirect(f"/posts/feeds/#post-{comment.post.id}")
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")

def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = PostForm(request.POST)

        if form.is_valid():
            # Post의 "user" 값은 request에서 가져와 자동 할당한다.
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Post를 생성한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage 객체를 생성한다.
            for image_file in request.FILES.getlist("images"):
                # request.FILES 또는 request.FILES.getlist()로 가져온 파일은
                # Model의 imageField 부분에 곧바로 할당한다.
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )
            tag_string = request.POST.get("tags")  # input의 name값을 적으면 input값을 들고 온다.
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    # get_or_create로 생성하거나 가져온 HashTag 객체를 Post의 tags에 추가한다
                    post.tags.add(tag)

            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # GET 요청일 때는 빈 form을 보여주도록 한다.
    else:
        form = PostForm()

    context = {"form": form}
    return render(request, "PortfolioA/posts/post_add.html", context)

def tags(request, tag_name):
    try:
        # HTML에서 요청한 해시태그(tag_name)에 해당하는 HashTag모델(DB)의 객체를 불러옴
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우, 빈 쿼리셋을 돌려준다.
        posts = Post.objects.none()
    else:   # 찾은경우 태그된 Post의 쿼리셋을 불러온다.
        posts = Post.objects.filter(tags=tag)

    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, 'PortfolioA/posts/tags.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "PortfolioA/posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아료를 누른 Post 목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제한다
        user.like_posts.remove(post)

    # 존재하지 않는다면 좋아요 목록에 추가한다
    else:
        user.like_posts.add(post)

    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드 페이지에서 해당 Post 위치로 이동한다.
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)

PortfolioA/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LoginForm, SignupForm
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.http import HttpResponseRedirect
from django.urls import reverse



def login_view(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")

    if request.method == "POST":
        form = LoginForm(data=request.POST)

        # LoginForm에 전달된 데이터가 유효하다면
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 있다면
            if user:
                # 로그인 처리 후, 피드 페이지로 redirect
                login(request, user)
                return redirect("/posts/feeds/")
            else:
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다. ")

        # 어떤 경우든 실패한 경우(데이터 검증, 사용자 검사 과정에서) 다시 LoginForm을 사용한 로그인 페이지 렌더링
        context = {"form": form}
        return render(request, "PortfolioA/users/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form}
        return render(request, "PortfolioA/users/login.html", context)

def logout_view(request):
    logout(request)  # GET, POST 요청에 관계없이 동작한다.
    return redirect("/users/login/")  # 로그아웃 처리 후, 로그인 페이지로 이동한다.

def signup(request):
    # POST 요청 시, form이 유효하다면 최종적으로 redirect 처리된다
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/posts/feeds/")
        # POST 요청에서 form이 유효하지 않다면, 아래의 context = ... 부분으로 이동한다.

    # GET 요청 시, 빈 form을 생성한다.
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "PortfolioA/users/signup.html", context)

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    context = {
        "user": user,
    }
    return render(request, "PortfolioA/users/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "PortfolioA/users/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "PortfolioA/users/following.html", context)

def follow(request, user_id):
    # 로그인한 유저
    user = request.user
    # 팔로우하려는 유저
    target_user = get_object_or_404(User, id=user_id)

    # 팔로우하려는 유저가 이미 자신의 팔로잉 목록에 있는 경우
    if target_user in user.following.all():
        # 팔로잉 목록에서 제거
        user.following.remove(target_user)

    # 팔로우하려는 유저가 자신의 팔로잉 목록에 없는 경우
    else:
        # 팔로잉 목록에 추가
        user.following.add(target_user)

    # 팔로우 토글 후 이동할 URL이 전달되었다면 해당 주소로,
    # 전달되지 않았다면 로그인 한 유저의 프로필 페이지로 이동
    url_next = request.GET.get("next") or reverse("users:profile", args=[user.id])
    return HttpResponseRedirect(url_next)

templates/PortfolioA/posts/feeds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{% extends 'PortfolioA/base_slider.html' %}
</head>
<body>
{% block content %}

{% load custom_tags %}
  <div id="feeds" class="post-container">
      {%for post in posts %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include 'PortfolioA/posts/post.html' with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
      {% endfor %}
  </div>
{% endblock %}


</body>
</html>

templates/PortfolioA/posts/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
          <article id="post-{{ post.id }}" class="post">
              <header class="post-header">
                  <a href="{% url 'users:profile' user_id=post.user.id %}">
                  {% if post.user.profile_image %}
                    <img src="{{ post.user.profile_image.url }}">
                  {% endif %}
                    <span>{{ post.user.username }}</span>
                  </a>
                  <!-- 글의 작성자가 로그인한 사용자라면 팔로우 버튼을 표시하지 않는다. -->
                  <!-- (자기 자신을 팔로후하는 것을 방지 -->
                  {% if user != post.user %}
                    <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                          <!-- 이 Post의 작성자가 이미 자신의 팔로잉 목록에 포함된 경우 -->
                            {% if post.user in user.following.all %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
              </header>

            <!== 이미지 슬라이드 영역 시작-->
              <div class="post-images splide">
                  <div class="splide__track">
                      <ul class="splide__list">
                          {% for image in post.postimage_set.all %}
                            {% if image.photo %}
                            <li class="splide__slide">
                                <img src="{{ image.photo.url }}">
                            </li>
                            {% endif %}
                          {% endfor %}
                      </ul>
                  </div>
              </div>
            <!-- 이미지 슬라이드 영역 종료-->
                  <div class="post-content">
                    {{ post.content|linebreaksbr }}
                      <div class="post-tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                        {% endfor %}
                      </div>
                </div>
                <div class="post-buttons">
                  <form action="{% url 'posts:post_like' post_id=post.id %}"?next="{{ action_redirect_url }}" method="POST">
                      {% csrf_token %}
                        <button type="submit"
                        {% if user in post.like_users.all %}
                        style="color: red,:"
                        {% endif %}>
                            <!-- Post의 related_name으로 지정한 like_users로 좋아요를 누른 사용자 수를 가져온다 -->
                            Likes({{ post.like_users.count }})
                        </button>
                  </form>
                  <span>Comments({{ post.comment_set.count }})</span>
                </div>

                <div class="post-comments">
                    <ul>
                    <!-- 각 Post에 연결된 PostComment들을 순회 -->
                    {% for comment in post.comment_set.all %}
                        <li>
                            <span>{{ comment.user.username }}</span>
                            <span>{{ comment.content }}</span>
                            {% if user == comment.user %}
                                <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                                    {% csrf_token %}
                                    <button type="submit">삭제</button>
                                </form>
                            {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                </div>

                <small>{{ post.created }}</small>
                <div class="post-comment-create">
                    <form method="POST" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
                        {% csrf_token %}
                        <input type="hidden" name="post" value="{{ post.id }}">
                        {{ comment_form.content }}
                        <button type="submit">게시</button>
                    </form>
                </div>
          </article>
</body>
</html>

templates/PortfolioA/posts/post_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'PortfolioA/base_nav.html' %}

{% block content %}
<div id="post-add">
  <h1>Post 작성</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_images">이미지</label>
            <input id="id_images" name="images" type="file" multiple>
        </div>
        {{ form.as_p }}
        <div>
            <label for="id_tags">해시태그</label>
            <input id="id_tags" name="tags"
                    type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
        </div>
        <button type="submit">게시</button>
    </form>
</div>
{% endblock %}
</body>
</html>

templates/PortfolioA/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'PortfolioA/base_slider.html' %}
{% block content %}
<div id="feeds" class="post-container">
    {% url 'posts:post_detail' post.id as action_redirect_to %}
    {% include 'PortfolioA/posts/post.html' with action_redirect_url=action_redirect_to %}
</div>
{% endblock %}
</body>
</html>

templates/PortfolioA/posts/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'PortfolioA/base_nav.html' %}
{% block content %}

<div id="tags">
  <header class="tags-header">
    <h2>#{{ tag_name }}</h2>
    <div>게시물 {{ posts.count }}</div>
  </header>
  <div class="post-grid-container">
    {% for post in posts %}
      {% if post.postimage_set.first and post.postimage_set.first.photo %}
      <div class="post-grid">
        <a href="{% url 'posts:post_detail' post_id=post.id %}">
          <img src="{{ post.postimage_set.first.photo.url }}" alt="">
        </a>
      </div>
      {% endif %}
      {% empty %}
        <p>검색된 게시물이 없습니다</p>
    {% endfor %}
  </div>
</div>
{% endblock %}
</body>
</html>
